version: "3"
services:
  vendor-portal:
    image: vikas1607/selenium1234
    environment:
    - BROWSER = chrome
    - HUB_HOST=hub    
    - THREAD_COUNT=1
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: vikas1607/selenium1234
    environment:
    - BROWSER = firefox
    - HUB_HOST=hub    
    - THREAD_COUNT=1
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - ./output/flight-reservation:/home/selenium-docker/test-output     